"""Initial tables

Revision ID: fb2c48e6d314
Revises: 
Create Date: 2025-04-20 13:45:24.432755

"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.resolve()))

from typing import Sequence, Union
from datetime import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.auth import get_password_hash  # Импорт функции для хеширования паролей


# revision identifiers, used by Alembic.
revision: str = 'fb2c48e6d314'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('patronymic', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('student', 'teacher', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('students',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teachers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('lecture', 'practice', name='subject_types'), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('lecture', 'practice', 'assignment', name='material_types'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('deadline > CURRENT_TIMESTAMP', name='check_future_deadline'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_subject',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'subject_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='check_time_order'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'graded', 'rejected', name='submission_status'), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('grade BETWEEN 0 AND 100', name='grade_range_check'),
    sa.ForeignKeyConstraint(['material_id'], ['course_materials.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    users_table = sa.table(
        'users',
        sa.Column('id', sa.Integer),
        sa.Column('email', sa.String),
        sa.Column('first_name', sa.String),
        sa.Column('last_name', sa.String),
        sa.Column('hashed_password', sa.String),
        sa.Column('role', sa.Enum('student', 'teacher', name='user_roles')),
        sa.Column('is_active', sa.Boolean)
    )

    groups_table = sa.table(
        'groups',
        sa.Column('id', sa.Integer),
        sa.Column('number', sa.String)
    )

    teachers_table = sa.table(
        'teachers',
        sa.Column('user_id', sa.Integer),
        sa.Column('position', sa.String)
    )

    students_table = sa.table(
        'students',
        sa.Column('user_id', sa.Integer),
        sa.Column('group_id', sa.Integer)
    )

    subjects_table = sa.table(
        'subjects',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.String),
        sa.Column('type', sa.Enum('lecture', 'practice', name='subject_types')),
        sa.Column('teacher_id', sa.Integer)
    )

    group_subject_table = sa.table(
        'group_subject',
        sa.Column('group_id', sa.Integer),
        sa.Column('subject_id', sa.Integer)
    )

    course_materials_table = sa.table(
        'course_materials',
        sa.Column('id', sa.Integer),
        sa.Column('title', sa.String),
        sa.Column('file_path', sa.String),
        sa.Column('type', sa.Enum('lecture', 'practice', 'assignment', name='material_types')),
        sa.Column('deadline', sa.DateTime),
        sa.Column('subject_id', sa.Integer),
        sa.Column('group_id', sa.Integer)
    )

    # Вставка данных
    op.bulk_insert(users_table,
                   [
                       {
                           "email": "teacher@edu.ru",
                           "first_name": "Препод",
                           "last_name": "Преподов",
                           "hashed_password": get_password_hash("teacher123"),
                           "role": "teacher",
                           "is_active": True
                       },
                       {
                           "email": "student@edu.ru",
                           "first_name": "Студент",
                           "last_name": "Студентов",
                           "hashed_password": get_password_hash("student456"),
                           "role": "student",
                           "is_active": True
                       }
                   ]
                   )

    op.bulk_insert(groups_table,
                   [{"number": "ГРУЗ-200"}]
                   )

    op.bulk_insert(teachers_table,
                   [{"user_id": 1, "position": "Профессор"}]
                   )

    op.bulk_insert(students_table,
                   [{"user_id": 2, "group_id": 1}]
                   )

    op.bulk_insert(subjects_table,
                   [{
                       "name": "Работа с данными",
                       "type": "practice",
                       "teacher_id": 1
                   }]
                   )

    op.bulk_insert(group_subject_table,
                   [{"group_id": 1, "subject_id": 1}]
                   )

    op.bulk_insert(course_materials_table,
                   [{
                       "title": "Введение в SQL",
                       "file_path": "/materials/sql_intro.pdf",
                       "type": "lecture",
                       "deadline": datetime(2025, 12, 12, 12, 0),
                       "subject_id": 1,
                       "group_id": 1
                   }]
                   )



def downgrade() -> None:
    # Удаление данных
    op.execute("DELETE FROM course_materials")
    op.execute("DELETE FROM group_subject")
    op.execute("DELETE FROM subjects")
    op.execute("DELETE FROM students")
    op.execute("DELETE FROM teachers")
    op.execute("DELETE FROM groups")
    op.execute("DELETE FROM users")

    # Удаление таблиц
    op.drop_table('assignment_submissions')
    op.drop_table('schedules')
    op.drop_table('group_subject')
    op.drop_table('course_materials')
    op.drop_table('subjects')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('users')
    op.drop_table('groups')

    # Удаление ENUM-типов
    op.execute("DROP TYPE IF EXISTS user_roles")
    op.execute("DROP TYPE IF EXISTS subject_types")
    op.execute("DROP TYPE IF EXISTS material_types")
    op.execute("DROP TYPE IF EXISTS submission_status")
    # ### end Alembic commands ###
